name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "deploy", "dev" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}/go-chat-server

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Compute version
        id: vars
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/go-chat-server" | tr '[:upper:]' '[:lower:]')
          TAG=$(git rev-parse --short=8 HEAD)
          echo "image=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        run: |
          docker build -t "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}" -t "${{ steps.vars.outputs.image }}:latest" .
          docker push "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}"
          docker push "${{ steps.vars.outputs.image }}:latest"

  deploy-wsl:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to B via WSL
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LOCAL_HOST }}
          port: ${{ secrets.LOCAL_PORT }}
          username: ${{ secrets.LOCAL_USERNAME }}
          key: ${{ secrets.LOCAL_KEY }}
          script: |
            wsl -d Ubuntu -- bash << 'EOF'
            mkdir -p ~/.docker
            echo '{"credsStore":""}' > ~/.docker/config.json
            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
            cd /opt/go-chat-server
            docker compose pull
            docker compose up -d
            docker logout ghcr.io
            EOF