name: Test SSH to Local

on:
  workflow_dispatch:  # 수동 실행용
  push:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Test to B
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LOCAL_HOST }}
          port: ${{ secrets.LOCAL_PORT }}
          username: ${{ secrets.LOCAL_USERNAME }}
          key: ${{ secrets.LOCAL_KEY }}
          script: |
            powershell -ExecutionPolicy Bypass -File C:\Workspace\example.ps1
